### PR TITLE
Convert AuthenticateUserTicket to strong typing

### PR DESCRIPTION
**Pull request by Hona**
The possible responses are:

**Fail**
```json
{
   "response":{
      "error":{
         "errorcode":3,
         "errordesc":"Invalid parameter"
      }
   }
}
```

**Success**
```json
{
   "response":{
      "params":{
         "result":"OK",
         "steamid":"7650000000009496",
         "ownersteamid":"7650000000009496",
         "vacbanned":false,
         "publisherbanned":false
      }
   }
}
```

### CODE REVIEW

**Review by babelshift — APPROVED** [review]

**Comment by babelshift** [comment]
Thanks for the contribution!

**Comment by Hona** [comment]
No worries! 

I use this as a nuget package, so I'm just wondering when it would get updated?

**Comment by babelshift** [comment]
@Hona I've just pushed out 4.2.7. Let me know how it goes.

**Comment by Hona** [comment]
Ok I just tested it, works great! Thanks for pushing it out

**Pull request merged**
