### PR TITLE
Refactored to allow injecting custom HttpClient. Also some cleanup.

### PR DESCRIPTION
**Pull request by babelshift**
- Refactored stack to allow for injecting custom `HttpClient` from the beginning. This will allow consumers to manage their own customizations and lifecycles of the `HttpClient` instance.
- Created factory class to make it easier to instantiate web interfaces for communicating with Steam Web API endpoints.
- General cleanup.

### CODE REVIEW

**Comment by dedmen** [comment]
Forgot to update Readme.md which still says `new SteamUser("<devkey>")` which doesn't work anymore.
Going through `CreateSteamWebInterface` is pretty unclear unless one reads the changes in this PR.

**Comment by babelshift** [comment]
Thanks for the heads up. I'll get this updated as soon as I can.

**Comment by babelshift** [comment]
@dedmen 
Sorry about the embarrassing delay on updating the documentation. #76 updates the samples.

**Comment by dedmen** [comment]
Thanks! Have a nice weekend.

**Pull request merged**
